import { assertSameOrigin, audit, json, readJson, requireAuth } from '../../_lib/auth.js';
import { aiProviderErrorJson, runStructuredAI } from '../../_lib/ai-gateway.js';
import { aiCredentialsSchemaError, buildUserAIEnv } from '../../_lib/ai-credentials.js';
import { canonicalDocumentType, normalizeExtractedDocument, parseDocumentTextDeterministic } from '../../_lib/document-intelligence.js';

const itemSchema={type:'object',additionalProperties:false,properties:{sku_code:{type:'string'},description:{type:'string'},quantity:{type:'number'},unit_price:{type:'number'},line_total:{type:'number'},currency:{type:'string'}},required:['sku_code','description','quantity','unit_price','line_total','currency']};
const schema={type:'object',additionalProperties:false,properties:{document_type:{type:'string'},document_no:{type:'string'},seller:{type:'string'},buyer:{type:'string'},currency:{type:'string'},amount:{type:'number'},incoterm:{type:'string'},payment_terms:{type:'string'},shipping_marks:{type:'string'},package_count:{type:'number'},quantity:{type:'number'},goods_description:{type:'string'},pol:{type:'string'},pod:{type:'string'},vessel:{type:'string'},voyage:{type:'string'},on_board_date:{type:'string'},clean_status:{type:'string'},bl_no:{type:'string'},awb_no:{type:'string'},issue_date:{type:'string'},items:{type:'array',items:itemSchema}},required:['document_type','document_no','seller','buyer','currency','amount','incoterm','payment_terms','shipping_marks','package_count','quantity','goods_description','pol','pod','vessel','voyage','on_board_date','clean_status','bl_no','awb_no','issue_date','items']};
const clean=(v,n=120000)=>String(v??'').trim().slice(0,n);
function merge(base,ai,type){const normalized=normalizeExtractedDocument(ai,type),out={...base};for(const[k,v]of Object.entries(normalized)){if(Array.isArray(v)){if(v.length)out[k]=v}else if(typeof v==='number'){if(v!==0||!out[k])out[k]=v}else if(clean(v,12000))out[k]=v}return normalizeExtractedDocument(out,type)}
async function limit(context,auth){const max=Math.max(1,Math.min(1000,Number(context.env.AI_DOCUMENT_DAILY_LIMIT||120))),since=new Date(Date.now()-86400000).toISOString();const row=await context.env.DB.prepare("SELECT COUNT(*) AS count FROM audit_logs WHERE tenant_id=? AND user_id=? AND action='ai.document.parse' AND created_at>=?").bind(auth.tenant.id,auth.user.id,since).first();return Number(row?.count||0)>=max?json({ok:false,error:'ai_daily_limit_reached',limit:max},429):null}

export async function onRequestPost(context){
  const originError=assertSameOrigin(context.request);if(originError)return originError;const {response,auth}=await requireAuth(context,'ai.use');if(response)return response;
  let body;try{body=await readJson(context.request)}catch{return json({ok:false,error:'invalid_json'},400)}const rawText=clean(body?.rawText,120000),type=canonicalDocumentType(body?.type);if(rawText.length<10)return json({ok:false,error:'document_text_required'},400);
  const deterministic=parseDocumentTextDeterministic(rawText,type);if(body?.useAI===false)return json({ok:true,mode:'deterministic',parsed:deterministic,provider:null,model:null});const limitError=await limit(context,auth);if(limitError)return limitError;
  let userAI;try{userAI=await buildUserAIEnv(context,auth)}catch(error){const e=aiCredentialsSchemaError(error);return json(e,e.error==='ai_credentials_schema_not_ready'?503:500)}
  const prompt=['Extract this foreign-trade document into the exact schema. Only use facts present in the supplied document text. Never infer missing shipment events, clean status, quantities, amounts, ports, dates, parties, or document numbers from general knowledge. Use empty string or 0 when absent.',`Expected document type: ${type}.`,`Deterministic extraction from the same source: ${JSON.stringify(deterministic)}`,`Source text:\n${rawText}`].join('\n\n');
  try{const result=await runStructuredAI(userAI.env,{task:'draft',providerId:String(body?.providerId||''),schema,maxTokens:3600,system:'You are a document extraction engine for B2B foreign trade. Extract source-backed structured data only. Do not perform legal interpretation or compliance advice.',prompt});const parsed=merge(deterministic,result.data,type),credentialScope=userAI.personalIds.has(result.provider.id)?'personal':'workspace';await audit(context,{tenantId:auth.tenant.id,userId:auth.user.id},'ai.document.parse','document',null,null,{type,provider:result.provider.id,model:result.model,credentialScope,documentNo:parsed.document_no||null});return json({ok:true,mode:'ai+deterministic',parsed,provider:result.provider.id,providerName:result.provider.name,model:result.model,credentialScope,usage:result.usage||null})}catch(error){const e=aiProviderErrorJson(error);return json({ok:true,mode:'deterministic-fallback',parsed:deterministic,provider:null,model:null,aiError:e.body},200)}
}
