import { assertSameOrigin, audit, json, randomId, readJson, requireAuth } from '../../_lib/auth.js';
import { clean, commercialSchemaError, normalizeDocument } from '../../_lib/commercialdata.js';

const TYPES=new Set(['PI','CI','PL','Contract','Shipping Instruction','Shipping Mark']);
async function snapshotOrder(DB,tenantId,orderId){
  const order=await DB.prepare(`SELECT o.*,c.legal_name AS company_name,c.website,c.country_code,c.city,ct.full_name AS contact_name,ct.email AS contact_email FROM orders o JOIN companies c ON c.id=o.company_id AND c.tenant_id=o.tenant_id LEFT JOIN contacts ct ON ct.id=o.contact_id AND ct.tenant_id=o.tenant_id WHERE o.id=? AND o.tenant_id=? LIMIT 1`).bind(orderId,tenantId).first();if(!order)return null;
  const items=await DB.prepare(`SELECT oi.*,s.code AS sku_code,s.variant,s.color,s.size,p.name AS product_name FROM order_items oi JOIN skus s ON s.id=oi.sku_id AND s.tenant_id=oi.tenant_id LEFT JOIN products p ON p.id=s.product_id AND p.tenant_id=s.tenant_id WHERE oi.order_id=? AND oi.tenant_id=? ORDER BY oi.created_at`).bind(orderId,tenantId).all();
  const packageRows=await DB.prepare(`SELECT sp.*,s.code AS sku_code FROM sku_packages sp JOIN skus s ON s.id=sp.sku_id AND s.tenant_id=sp.tenant_id JOIN order_items oi ON oi.sku_id=sp.sku_id AND oi.tenant_id=sp.tenant_id WHERE oi.order_id=? AND sp.tenant_id=? ORDER BY s.code,sp.package_code`).bind(orderId,tenantId).all();
  return {order:{id:order.id,orderNo:order.order_no,poNumber:order.po_number||'',currency:order.currency,incoterm:order.incoterm||'',port:order.port||'',paymentTerms:order.payment_terms||'',amount:Number(order.amount||0),deposit:Number(order.deposit||0),balance:Number(order.balance||0),productionDate:order.production_date||'',etd:order.etd||'',eta:order.eta||'',status:order.status},customer:{companyId:order.company_id,companyName:order.company_name,website:order.website||'',country:order.country_code||'',city:order.city||'',contactId:order.contact_id||null,contactName:order.contact_name||'',contactEmail:order.contact_email||''},items:(items.results||[]).map(i=>({skuId:i.sku_id,skuCode:i.sku_code,product:i.product_name||'',variant:i.variant||'',color:i.color||'',size:i.size||'',quantity:Number(i.quantity||0),unitPrice:Number(i.unit_price||0),lineTotal:Number(i.line_total||0),currency:i.currency||order.currency})),packages:(packageRows.results||[]).map(p=>({skuId:p.sku_id,skuCode:p.sku_code,packageCode:p.package_code,quantityPerSet:Number(p.quantity_per_set||1),length:Number(p.length||0),width:Number(p.width||0),height:Number(p.height||0),dimensionUnit:p.dimension_unit||'CM',grossWeight:Number(p.gross_weight||0),weightUnit:p.weight_unit||'KG'}))};
}

export async function onRequestGet(context){const {response,auth}=await requireAuth(context,'documents.read');if(response)return response;const orderId=new URL(context.request.url).searchParams.get('orderId')||'';try{const params=[auth.tenant.id];let where='d.tenant_id=?';if(orderId){where+=' AND d.order_id=?';params.push(orderId)}const r=await context.env.DB.prepare(`SELECT d.*,(SELECT MAX(version_no) FROM document_versions v WHERE v.document_id=d.id AND v.tenant_id=d.tenant_id) latest_version FROM documents d WHERE ${where} ORDER BY datetime(d.updated_at) DESC LIMIT 2000`).bind(...params).all();return json({ok:true,documents:(r.results||[]).map(normalizeDocument)})}catch(error){const s=commercialSchemaError(error);return json(s,s.error==='commercial_schema_not_ready'?503:500)}}

export async function onRequestPost(context){
  const originError=assertSameOrigin(context.request);if(originError)return originError;const {response,auth}=await requireAuth(context,'documents.write');if(response)return response;let body;try{body=await readJson(context.request)}catch{return json({ok:false,error:'invalid_json'},400)}const type=clean(body?.type,40),orderId=clean(body?.orderId,120);if(!TYPES.has(type))return json({ok:false,error:'document_type_invalid'},400);if(!orderId)return json({ok:false,error:'order_required'},400);
  const tenantId=auth.tenant.id,now=new Date().toISOString();try{const snap=await snapshotOrder(context.env.DB,tenantId,orderId);if(!snap)return json({ok:false,error:'order_not_found'},404);snap.documentType=type;snap.generatedAt=now;snap.generatedBy=auth.user.id;let doc=await context.env.DB.prepare('SELECT * FROM documents WHERE tenant_id=? AND order_id=? AND document_type=? ORDER BY created_at LIMIT 1').bind(tenantId,orderId,type).first();const docId=doc?.id||randomId('doc');const versionRow=doc?await context.env.DB.prepare('SELECT COALESCE(MAX(version_no),0) max_version FROM document_versions WHERE tenant_id=? AND document_id=?').bind(tenantId,docId).first():null;const version=Number(versionRow?.max_version||0)+1,docNo=doc?.document_no||`${type.replace(/\s+/g,'-').toUpperCase()}-${snap.order.orderNo}`;const stmts=[];if(!doc)stmts.push(context.env.DB.prepare(`INSERT INTO documents(id,tenant_id,document_type,document_no,company_id,order_id,storage_key,mime_type,metadata_json,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,NULL,'application/json',?,'Draft',?,?,?)`).bind(docId,tenantId,type,docNo,snap.customer.companyId,orderId,JSON.stringify(snap),auth.user.id,now,now));else stmts.push(context.env.DB.prepare(`UPDATE documents SET metadata_json=?,status='Draft',updated_at=? WHERE id=? AND tenant_id=?`).bind(JSON.stringify(snap),now,docId,tenantId));stmts.push(context.env.DB.prepare(`INSERT INTO document_versions(id,tenant_id,document_id,version_no,snapshot_json,storage_key,mime_type,created_by,created_at) VALUES(?,?,?,?,?,NULL,'application/json',?,?)`).bind(randomId('docv'),tenantId,docId,version,JSON.stringify(snap),auth.user.id,now));await context.env.DB.batch(stmts);doc=await context.env.DB.prepare(`SELECT d.*,? latest_version FROM documents d WHERE d.id=? AND d.tenant_id=? LIMIT 1`).bind(version,docId,tenantId).first();const normalized=normalizeDocument(doc);await audit(context,{tenantId,userId:auth.user.id},version===1?'document.create':'document.revision','document',docId,null,{...normalized,version});return json({ok:true,document:normalized,version,snapshot:snap},version===1?201:200)}catch(error){const s=commercialSchemaError(error);return json(s,s.error==='commercial_schema_not_ready'?503:500)}}
