import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync}from'node:sqlite';import{sha256}from'../functions/_lib/auth.js';import*as ws from'../functions/api/cargo-workspaces.js';import*as shares from'../functions/api/cargo-shares.js';import*as publicShare from'../functions/api/cargo-share-public.js';
function db(){const sql=new DatabaseSync(':memory:');sql.exec(`CREATE TABLE sessions(id TEXT,tenant_id TEXT,user_id TEXT,token_hash TEXT,expires_at TEXT,revoked_at TEXT,last_seen_at TEXT);CREATE TABLE users(id TEXT,email TEXT,display_name TEXT,status TEXT);CREATE TABLE tenants(id TEXT,name TEXT,slug TEXT,status TEXT);CREATE TABLE roles(id TEXT,tenant_id TEXT,role_key TEXT,name TEXT,permissions_json TEXT);CREATE TABLE user_roles(user_id TEXT,role_id TEXT);`);const DB={prepare(q){const statement=sql.prepare(q);let args=[];return {bind(...v){args=v;return this;},async run(){return statement.run(...args);},async first(){return statement.get(...args)||null;},async all(){return {results:statement.all(...args)};}};},async batch(stmts){sql.exec('BEGIN');try{const out=await Promise.all(stmts.map(s=>s.run()));sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};return {sql,DB};}
async function fixture(){const {sql,DB}=db();for(const [id,permission]of [['a','*'],['b','*'],['reader','container.read']]){sql.prepare('INSERT INTO sessions VALUES(?,?,?,?,?,NULL,NULL)').run(id,id,id,await sha256(id),'2099-01-01');sql.prepare('INSERT INTO users VALUES(?,?,?,?)').run(id,id+'@test.example',id,'active');sql.prepare('INSERT INTO tenants VALUES(?,?,?,?)').run(id,id,id,'active');sql.prepare('INSERT INTO roles VALUES(?,?,?,?,?)').run(id,id,id,id,JSON.stringify([permission]));sql.prepare('INSERT INTO user_roles VALUES(?,?)').run(id,id);}
const ctx=(actor='a',body,method='POST',path='',origin='https://os.example')=>({env:{DB,SESSION_SECRET:'test-secret'},waitUntil(){},request:new Request('https://os.example/api/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:'__Host-aftos_session='+actor},body:body===undefined?undefined:JSON.stringify(body)})});return {ctx,DB};}
const payload=JSON.stringify({format:'cargo-fit-workspace',version:1,inputs:{products:[{sku:'synthetic'}]}});
test('authentication, permissions and CSRF enforced before writing',async()=>{const {ctx}=await fixture();assert.equal((await ws.onRequestPost(ctx('unknown',{name:'n',payload}))).status,401);assert.equal((await ws.onRequestPost(ctx('reader',{name:'n',payload}))).status,403);assert.equal((await ws.onRequestPost(ctx('a',{name:'n',payload},'POST','','https://evil.example'))).status,403);});
test('versions append and tenant cannot read another workspace',async()=>{const {ctx}=await fixture();const first=await(await ws.onRequestPost(ctx('a',{name:'n',payload}))).json();assert.ok(first.id);await ws.onRequestPost(ctx('a',{name:'n',payload}));const list=await(await ws.onRequestGet(ctx('a',undefined,'GET'))).json();assert.deepEqual(list.workspaces.map(w=>w.version).sort(),[1,2]);assert.equal((await ws.onRequestGet(ctx('b',undefined,'GET','?id='+first.id))).status,404);});
test('read-only token expires and can only be revoked by matching tenant',async()=>{const {ctx,DB}=await fixture();const first=await(await ws.onRequestPost(ctx('a',{name:'n',payload}))).json();assert.equal((await shares.onRequestPost(ctx('b',{workspaceId:first.id,days:7}))).status,404);const share=await(await shares.onRequestPost(ctx('a',{workspaceId:first.id,days:7}))).json();assert.equal(share.token.length,64);const body={id:share.id,token:share.token};assert.equal((await publicShare.onRequestPost(ctx('unknown',body))).status,200);assert.equal((await publicShare.onRequestPost(ctx('unknown',{...body,token:'0'.repeat(64)}))).status,404);await shares.onRequestDelete(ctx('b',{id:share.id},'DELETE'));assert.equal((await publicShare.onRequestPost(ctx('unknown',body))).status,200);await shares.onRequestDelete(ctx('a',{id:share.id},'DELETE'));assert.equal((await publicShare.onRequestPost(ctx('unknown',body))).status,404);await DB.prepare('UPDATE cargo_shares SET revoked_at=NULL,expires_at=? WHERE id=?').bind('2000-01-01',share.id).run();assert.equal((await publicShare.onRequestPost(ctx('unknown',body))).status,404);});
test('oversized and malformed data rejected',async()=>{const {ctx}=await fixture();assert.equal((await ws.onRequestPost(ctx('a',{name:'n',payload:'x'.repeat(1024*1024+1)}))).status,413);assert.equal((await ws.onRequestPost(ctx('a',{name:'n',payload:'{}'}))).status,400);});

 test('OS export validates every referenced SKU, package and order tenant',async()=>{const {validateCargoReferences}=await import('../functions/_lib/cargo.js');const {sql,DB}=db();sql.exec("CREATE TABLE skus(id TEXT,tenant_id TEXT);CREATE TABLE sku_packages(id TEXT,sku_id TEXT,tenant_id TEXT);CREATE TABLE orders(id TEXT,tenant_id TEXT);INSERT INTO skus VALUES('s','a'),('other','b');INSERT INTO sku_packages VALUES('pkg','s','a');INSERT INTO orders VALUES('order','a');");const body={placed:[{skuId:'s',pkgId:'pkg',x:0,y:0,z:0,l:10,w:10,h:10,weight:1}],sourceOrderIds:['order']};await validateCargoReferences(DB,'a',body);await assert.rejects(validateCargoReferences(DB,'b',body));await assert.rejects(validateCargoReferences(DB,'a',{...body,placed:[{...body.placed[0],skuId:'other'}]}));await assert.rejects(validateCargoReferences(DB,'a',{...body,sourceOrderIds:['missing']}));});
