const clean=(v,n=12000)=>String(v??'').trim().slice(0,n);
const DOC_TYPES=new Set(['CI','PL','BL','AWB','SEA_WAYBILL','INSURANCE','COO','INSPECTION','BENEFICIARY_CERT','OTHER']);
function permit(v){const s=clean(v,100).toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ');if(!s)return'unknown';if(/not allowed|prohibited|not permitted|forbidden|without/.test(s))return'not allowed';if(/allowed|permitted|acceptable|yes/.test(s))return'allowed';return'unknown'}
function docType(v){const s=clean(v,100).toUpperCase().replace(/[\s/-]+/g,'_');if(DOC_TYPES.has(s))return s;if(/BILL.*LADING|OCEAN.*B\/L|B\/L/.test(s))return'BL';if(/AIR.*WAYBILL|AWB/.test(s))return'AWB';if(/COMMERCIAL.*INVOICE|INVOICE/.test(s))return'CI';if(/PACKING.*LIST/.test(s))return'PL';if(/INSURANCE/.test(s))return'INSURANCE';if(/ORIGIN/.test(s))return'COO';if(/INSPECTION|CERTIFICATE.*QUALITY|CERTIFICATE.*WEIGHT/.test(s))return'INSPECTION';if(/BENEFICIARY/.test(s))return'BENEFICIARY_CERT';return'OTHER'}
export const LC_MEDIA_SCHEMA={type:'object',additionalProperties:false,properties:{lcNo:{type:'string'},applicantName:{type:'string'},beneficiaryName:{type:'string'},currency:{type:'string'},amount:{type:'number'},issueDate:{type:'string'},expiryDate:{type:'string'},presentationPlace:{type:'string'},latestShipmentDate:{type:'string'},partialShipment:{type:'string'},transshipment:{type:'string'},goodsDescription:{type:'string'},pol:{type:'string'},pod:{type:'string'},presentationPeriod:{type:'string'},additionalConditions:{type:'string'},requiredDocuments:{type:'array',items:{type:'object',additionalProperties:false,properties:{documentType:{type:'string'},description:{type:'string'},originals:{type:'integer'},copies:{type:'integer'},conditionText:{type:'string'}},required:['documentType','description','originals','copies','conditionText']}}},required:['lcNo','applicantName','beneficiaryName','currency','amount','issueDate','expiryDate','presentationPlace','latestShipmentDate','partialShipment','transshipment','goodsDescription','pol','pod','presentationPeriod','additionalConditions','requiredDocuments']};
export function normalizeLCMediaExtraction(input={}){
  const docs=Array.isArray(input.requiredDocuments)?input.requiredDocuments.slice(0,80).map((d,i)=>({documentType:docType(d?.documentType),description:clean(d?.description,5000),originals:Math.max(0,Math.min(99,Math.trunc(Number(d?.originals||0)))),copies:Math.max(0,Math.min(99,Math.trunc(Number(d?.copies||0)))),conditions:{text:clean(d?.conditionText,5000),source:'multimodal-ai'},sortOrder:i})):[];
  return{lcNo:clean(input.lcNo,200),applicantName:clean(input.applicantName,1000),beneficiaryName:clean(input.beneficiaryName,1000),currency:clean(input.currency,20).toUpperCase(),amount:Number.isFinite(Number(input.amount))?Number(input.amount):0,issueDate:clean(input.issueDate,40),expiryDate:clean(input.expiryDate,40),presentationPlace:clean(input.presentationPlace,1000),latestShipmentDate:clean(input.latestShipmentDate,40),partialShipment:permit(input.partialShipment),transshipment:permit(input.transshipment),goodsDescription:clean(input.goodsDescription,12000),pol:clean(input.pol,1000),pod:clean(input.pod,1000),presentationPeriod:clean(input.presentationPeriod,2000),additionalConditions:clean(input.additionalConditions,12000),requiredDocuments:docs};
}
