import { assertSameOrigin, audit, json, randomId, readJson, requireAuth } from '../../_lib/auth.js';
import { clean, dbError, integer, normalizeQuote, number, requireTenantEntity } from '../../_lib/masterdata.js';

function parse(body){const companyId=clean(body?.companyId,120),skuId=clean(body?.skuId,120);if(!companyId)return{error:'company_required'};if(!skuId)return{error:'sku_required'};const qty=Math.max(1,integer(body?.qty,1)),unitCost=Math.max(0,number(body?.unitCost)),unitPrice=Math.max(0,number(body?.unitPrice));return{value:{companyId,skuId,qty,unitCost,unitPrice,total:Math.max(0,number(body?.total,unitPrice*qty)),margin:Math.max(0,Math.min(100,number(body?.margin))),currency:clean(body?.currency,12)||'USD',incoterm:clean(body?.incoterm,32),status:clean(body?.status,40)||'Draft',costSnapshot:body?.costSnapshot&&typeof body.costSnapshot==='object'?body.costSnapshot:{}}}}
async function readQuote(context,id,tenantId){const row=await context.env.DB.prepare('SELECT * FROM quotes WHERE id=? AND tenant_id=? LIMIT 1').bind(id,tenantId).first();if(!row)return null;const items=await context.env.DB.prepare('SELECT * FROM quote_items WHERE quote_id=? AND tenant_id=? ORDER BY created_at').bind(id,tenantId).all();return normalizeQuote(row,items.results||[])}

export async function onRequestGet(context){const {response,auth}=await requireAuth(context,'quotes.read');if(response)return response;const rows=await context.env.DB.prepare('SELECT * FROM quotes WHERE tenant_id=? ORDER BY datetime(updated_at) DESC,quote_no DESC LIMIT 3000').bind(auth.tenant.id).all();const items=await context.env.DB.prepare('SELECT * FROM quote_items WHERE tenant_id=? ORDER BY quote_id,created_at').bind(auth.tenant.id).all();const map=new Map();for(const item of items.results||[]){const list=map.get(item.quote_id)||[];list.push(item);map.set(item.quote_id,list)}return json({ok:true,quotes:(rows.results||[]).map(r=>normalizeQuote(r,map.get(r.id)||[]))})}

export async function onRequestPost(context){const originError=assertSameOrigin(context.request);if(originError)return originError;const {response,auth}=await requireAuth(context,'quotes.write');if(response)return response;let body;try{body=await readJson(context.request)}catch(_){return json({ok:false,error:'invalid_json'},400)}const parsed=parse(body);if(parsed.error)return json({ok:false,error:parsed.error},400);const q=parsed.value;if(!await requireTenantEntity(context.env.DB,'companies',q.companyId,auth.tenant.id))return json({ok:false,error:'company_not_found'},404);if(!await requireTenantEntity(context.env.DB,'skus',q.skuId,auth.tenant.id))return json({ok:false,error:'sku_not_found'},404);const id=clean(body?.id,120)||randomId('q'),quoteNo=clean(body?.quoteNo,120)||`Q-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`,itemId=randomId('qi'),now=new Date().toISOString();try{await context.env.DB.batch([context.env.DB.prepare(`INSERT INTO quotes(id,tenant_id,quote_no,company_id,currency,incoterm,status,total,margin,cost_snapshot,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,auth.tenant.id,quoteNo,q.companyId,q.currency,q.incoterm||null,q.status,q.total,q.margin,JSON.stringify(q.costSnapshot),now,now),context.env.DB.prepare(`INSERT INTO quote_items(id,tenant_id,quote_id,sku_id,quantity,unit_cost,unit_price,currency,line_total,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'{}',?,?)`).bind(itemId,auth.tenant.id,id,q.skuId,q.qty,q.unitCost,q.unitPrice,q.currency,q.unitPrice*q.qty,now,now)])}catch(error){return dbError(error,'quote_create_failed')}const value=await readQuote(context,id,auth.tenant.id);await audit(context,{tenantId:auth.tenant.id,userId:auth.user.id},'quote.create','quote',id,null,value);return json({ok:true,quote:value},201)}
