import { assertSameOrigin, audit, json, readJson, requireAuth } from '../../_lib/auth.js';
import { clean, dbError, normalizeProduct } from '../../_lib/masterdata.js';

function parse(body){const name=clean(body?.name,200);if(!name)return{error:'product_name_required'};return{value:{name,category:clean(body?.category,160),series:clean(body?.series,120),hs:clean(body?.hs,64),material:clean(body?.material,160),market:clean(body?.market,80),status:clean(body?.status,40)||'active'}}}
async function row(context,id,tenantId){return context.env.DB.prepare('SELECT * FROM products WHERE id=? AND tenant_id=? LIMIT 1').bind(id,tenantId).first()}

export async function onRequestPut(context){const originError=assertSameOrigin(context.request);if(originError)return originError;const {response,auth}=await requireAuth(context,'product.catalog.write');if(response)return response;const id=clean(context.params?.id,120);const before=await row(context,id,auth.tenant.id);if(!before)return json({ok:false,error:'product_not_found'},404);let body;try{body=await readJson(context.request)}catch(_){return json({ok:false,error:'invalid_json'},400)}const parsed=parse(body);if(parsed.error)return json({ok:false,error:parsed.error},400);const p=parsed.value,now=new Date().toISOString();try{await context.env.DB.prepare(`UPDATE products SET name=?,category=?,series=?,default_hs_code=?,material=?,market=?,status=?,updated_at=? WHERE id=? AND tenant_id=?`).bind(p.name,p.category||null,p.series||null,p.hs||null,p.material||null,p.market||null,p.status,now,id,auth.tenant.id).run()}catch(error){return dbError(error,'product_update_failed')}const after=await row(context,id,auth.tenant.id);await audit(context,{tenantId:auth.tenant.id,userId:auth.user.id},'product.update','product',id,normalizeProduct(before),normalizeProduct(after));return json({ok:true,product:normalizeProduct(after)})}

export async function onRequestDelete(context){const originError=assertSameOrigin(context.request);if(originError)return originError;const {response,auth}=await requireAuth(context,'product.catalog.write');if(response)return response;const id=clean(context.params?.id,120);const before=await row(context,id,auth.tenant.id);if(!before)return json({ok:false,error:'product_not_found'},404);const refs=await context.env.DB.prepare('SELECT COUNT(*) AS count FROM skus WHERE product_id=? AND tenant_id=?').bind(id,auth.tenant.id).first();if(Number(refs?.count||0)>0)return json({ok:false,error:'product_has_skus'},409);try{await context.env.DB.prepare('DELETE FROM products WHERE id=? AND tenant_id=?').bind(id,auth.tenant.id).run()}catch(error){return dbError(error,'product_delete_failed')}await audit(context,{tenantId:auth.tenant.id,userId:auth.user.id},'product.delete','product',id,normalizeProduct(before),null);return json({ok:true,id})}
