import { assertSameOrigin, audit, json, randomId, readJson, requireAuth } from '../../_lib/auth.js';
import { boolInt, clean, dbError, integer, normalizePackage, normalizeSku, number, requireTenantEntity } from '../../_lib/masterdata.js';

function parsePackages(value){if(!Array.isArray(value)||!value.length)return{error:'package_required'};const seen=new Set(),packages=[];for(const raw of value.slice(0,100)){const code=clean(raw?.code,80)||String.fromCharCode(65+packages.length);if(seen.has(code.toLowerCase()))return{error:'duplicate_package_code'};seen.add(code.toLowerCase());const l=number(raw?.l),w=number(raw?.w),h=number(raw?.h);if(!(l>0&&w>0&&h>0))return{error:'invalid_package_dimensions'};packages.push({id:clean(raw?.id,120)||randomId('pkg'),code,qtyPerSet:Math.max(1,integer(raw?.qtyPerSet,1)),l,w,h,grossWeight:Math.max(0,number(raw?.grossWeight)),netWeight:raw?.netWeight==null?null:Math.max(0,number(raw.netWeight)),keepUpright:boolInt(raw?.keepUpright),stackable:boolInt(raw?.stackable,true),fragile:boolInt(raw?.fragile),maxStackLayers:raw?.maxStackLayers==null?null:Math.max(1,integer(raw.maxStackLayers,1)),maxTopLoad:raw?.maxTopLoad==null?null:Math.max(0,number(raw.maxTopLoad))})}return{value:packages}}
function parse(body){const productId=clean(body?.productId,120),code=clean(body?.code,120);if(!productId)return{error:'product_required'};if(!code)return{error:'sku_code_required'};const packages=parsePackages(body?.packages);if(packages.error)return packages;return{value:{productId,code,variant:clean(body?.variant,180),color:clean(body?.color,120),size:clean(body?.size,120),cost:Math.max(0,number(body?.cost)),currency:clean(body?.currency,12)||'USD',moq:Math.max(1,integer(body?.moq,1)),leadTime:body?.leadTime==null?null:Math.max(0,integer(body.leadTime)),hs:clean(body?.hs,64),status:clean(body?.status,40)||'active',packages:packages.value}}}

export async function onRequestGet(context){const {response,auth}=await requireAuth(context,'product.skus.read');if(response)return response;const [s,p]=await context.env.DB.batch([context.env.DB.prepare('SELECT * FROM skus WHERE tenant_id=? ORDER BY datetime(updated_at) DESC,code ASC LIMIT 5000').bind(auth.tenant.id),context.env.DB.prepare('SELECT * FROM sku_packages WHERE tenant_id=? ORDER BY sku_id,package_code LIMIT 10000').bind(auth.tenant.id)]);return json({ok:true,skus:(s.results||[]).map(normalizeSku),packages:(p.results||[]).map(normalizePackage)})}

export async function onRequestPost(context){const originError=assertSameOrigin(context.request);if(originError)return originError;const {response,auth}=await requireAuth(context,'product.skus.write');if(response)return response;let body;try{body=await readJson(context.request)}catch(_){return json({ok:false,error:'invalid_json'},400)}const parsed=parse(body);if(parsed.error)return json({ok:false,error:parsed.error},400);const s=parsed.value;if(!await requireTenantEntity(context.env.DB,'products',s.productId,auth.tenant.id))return json({ok:false,error:'product_not_found'},404);const id=clean(body?.id,120)||randomId('sku'),now=new Date().toISOString();const gross=s.packages.reduce((sum,p)=>sum+p.grossWeight*p.qtyPerSet,0);const statements=[context.env.DB.prepare(`INSERT INTO skus(id,tenant_id,product_id,code,variant,color,size,gross_weight,cost,currency,moq,lead_time,hs_code,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,auth.tenant.id,s.productId,s.code,s.variant||null,s.color||null,s.size||null,gross,s.cost,s.currency,s.moq,s.leadTime,s.hs||null,s.status,now,now),...s.packages.map(p=>context.env.DB.prepare(`INSERT INTO sku_packages(id,tenant_id,sku_id,package_code,quantity_per_set,length,width,height,dimension_unit,gross_weight,net_weight,weight_unit,rotatable_x,rotatable_y,rotatable_z,keep_upright,stackable,max_stack_layers,max_top_load,fragile) VALUES(?,?,?,?,?,?,?,?, 'CM',?,?, 'KG',1,1,1,?,?,?,?,?)`).bind(p.id,auth.tenant.id,id,p.code,p.qtyPerSet,p.l,p.w,p.h,p.grossWeight,p.netWeight,p.keepUpright,p.stackable,p.maxStackLayers,p.maxTopLoad,p.fragile))];try{await context.env.DB.batch(statements)}catch(error){return dbError(error,'sku_create_failed')}const row=await context.env.DB.prepare('SELECT * FROM skus WHERE id=? AND tenant_id=?').bind(id,auth.tenant.id).first();const pkgRows=await context.env.DB.prepare('SELECT * FROM sku_packages WHERE sku_id=? AND tenant_id=? ORDER BY package_code').bind(id,auth.tenant.id).all();const value=normalizeSku(row),packages=(pkgRows.results||[]).map(normalizePackage);await audit(context,{tenantId:auth.tenant.id,userId:auth.user.id},'sku.create','sku',id,null,{...value,packages});return json({ok:true,sku:value,packages},201)}
